close all
clear variables;

length = 0.4274;
width = 0.0177;
loop_radius = 0.1085;
gap = 0.0140;
tilt = 0;
tilt_axis = [1 0 0];

% Script generated by antennaDesigner 
% Define plot frequency 
plotFrequency = 137e6;
% Define frequency range 
freqRange = (123.3:1.37:150.7) * 1e6;
% Define antenna 
dc = dipoleCycloid('Length', length, 'Width', width, 'LoopRadius', loop_radius, 'Gap', gap, 'Tilt', tilt, 'TiltAxis', tilt_axis);
% show for reflector
figure;
show(dc);
saveas(gcf, 'cycloid_dipole_design.png')
% pattern for reflector
figure;
pattern(dc, plotFrequency);
saveas(gcf, 'cycloid_dipole_farfield.png')
% s11 for reflector
figure;
s = sparameters(dc, freqRange); 
fig = rfplot(s);
saveas(gcf, 'cycloid_dipole_s_parameters.png')
% azimuth for reflector
figure;
patternAzimuth(dc, plotFrequency)
saveas(gcf, 'cycloid_dipole_azimuth_radiation_pattern.png')
% elevation for reflector
figure;
patternElevation(dc, plotFrequency)
saveas(gcf, 'cycloid_dipole_elevation_radiation_pattern.png')
% current for reflector
figure;
current(dc, plotFrequency)
saveas(gcf, 'cycloid_dipole_current.png')
% impedance for reflector
figure;
impedance(dc, freqRange)
saveas(gcf, 'cycloid_dipole_impedance.png')

